### ISSUE TITLE
Typescript Declaration Files

### ISSUE THREAD

**Issue by weisrc** [dclipca/react-native-social-buttons#6]
Please add Typescript declaration files. Thank you!

**Comment by dclipca** [comment]
Will add as soon as I find some free time. In the meantime, anyone is welcome to add a poll request with TS declarations.

**Comment by dclipca** [comment]
I have no idea how to add TS declarations to repositories so if someone knows, please send a poll request.

**Comment by angelxmoreno** [comment]
I can take this on

**Comment by angelxmoreno** [comment]
PR open #9

**Comment by dclipca** [comment]
> PR open #9

I added you as a collaborator. Will give full repo access. Will take a bit to reset my NPM account due to deleting my gmail. Should take 2-3 days then I'll give you NPM access. Thank you once again, really impressive!
